version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public            # Monta el directorio /public
      - ./.next/static:/app/.next/static # Monta el directorio /_next/static

networks:
  frontend:
    driver: bridge
