version: '3'
services:
  web:
    image: verderaiz-website
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
