version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - HOST=0.0.0.0
      - "3000:3000"
    networks:
      - frontend
    environment:
      - NODE_ENV=production

networks:
  frontend:
    driver: bridge
