version: '3.8'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public            # Monta el directorio /public
      - ./.next/static:/app/.next/static # Monta el directorio /_next/static

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Monta tu configuración de Nginx
      - ./public:/app/public                         # Acceso a /public directamente
      - ./.next/static:/app/.next/static             # Acceso a /_next/static directamente
    networks:
      - frontend
    depends_on:
      - web

networks:
  frontend:
    driver: bridge
